/**
 * Xato kodlari — mijoz ilova aynan SHU kod bo'yicha xabarni o'z tilida ko'rsatadi.
 * Serverdagi `message` — faqat zaxira (log va debug uchun).
 * Kod bir marta belgilanadi va O'ZGARMAYDI: mobil ilovaning eski versiyalari
 * foydalanuvchilarda uzoq vaqt qolib ketadi.
 */
export const ErrorCode = {
  // --- umumiy ---
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  FORBIDDEN: 'FORBIDDEN',
  RATE_LIMITED: 'RATE_LIMITED',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',

  // --- autentifikatsiya ---
  AUTH_UNAUTHORIZED: 'AUTH_UNAUTHORIZED',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  AUTH_SESSION_REVOKED: 'AUTH_SESSION_REVOKED',
  AUTH_REFRESH_REUSED: 'AUTH_REFRESH_REUSED',

  // --- OTP ---
  OTP_INVALID_PHONE: 'OTP_INVALID_PHONE',
  OTP_COOLDOWN: 'OTP_COOLDOWN',
  OTP_TOO_MANY_REQUESTS: 'OTP_TOO_MANY_REQUESTS',
  OTP_NOT_FOUND: 'OTP_NOT_FOUND',
  OTP_EXPIRED: 'OTP_EXPIRED',
  OTP_INCORRECT: 'OTP_INCORRECT',
  OTP_TOO_MANY_ATTEMPTS: 'OTP_TOO_MANY_ATTEMPTS',
  OTP_SEND_FAILED: 'OTP_SEND_FAILED',

  // --- foydalanuvchi ---
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_BANNED: 'USER_BANNED',
  USER_SUSPENDED: 'USER_SUSPENDED',
  USER_PROFILE_INCOMPLETE: 'USER_PROFILE_INCOMPLETE',
  USER_ROLE_NOT_ALLOWED: 'USER_ROLE_NOT_ALLOWED',

  // --- haydovchi va transport ---
  DRIVER_NOT_VERIFIED: 'DRIVER_NOT_VERIFIED',
  VEHICLE_NOT_VERIFIED: 'VEHICLE_NOT_VERIFIED',
  VEHICLE_CAPACITY_EXCEEDED: 'VEHICLE_CAPACITY_EXCEEDED',
  VEHICLE_PLATE_TAKEN: 'VEHICLE_PLATE_TAKEN',
  VEHICLE_PLATE_INVALID: 'VEHICLE_PLATE_INVALID',
  VEHICLE_LOCKED_AFTER_VERIFY: 'VEHICLE_LOCKED_AFTER_VERIFY',
  VEHICLE_LIMIT_REACHED: 'VEHICLE_LIMIT_REACHED',

  // --- ma'lumotnoma (kategoriya, transport turi, kuzov) ---
  REFERENCE_NOT_FOUND: 'REFERENCE_NOT_FOUND',

  // --- yuk ---
  LOAD_NOT_ACCEPTING_OFFERS: 'LOAD_NOT_ACCEPTING_OFFERS',
  LOAD_ALREADY_ASSIGNED: 'LOAD_ALREADY_ASSIGNED',
  LOAD_ALREADY_CLOSED: 'LOAD_ALREADY_CLOSED',
  LOAD_HAS_ORDER: 'LOAD_HAS_ORDER',
  LOAD_PICKUP_TIME_PASSED: 'LOAD_PICKUP_TIME_PASSED',
  LOAD_TIME_WINDOW_INVALID: 'LOAD_TIME_WINDOW_INVALID',
  LOAD_PRICE_REQUIRED: 'LOAD_PRICE_REQUIRED',
  LOAD_NOT_PUBLISHABLE: 'LOAD_NOT_PUBLISHABLE',
  LOAD_NOT_EDITABLE: 'LOAD_NOT_EDITABLE',
  LOAD_ACTIVE_LIMIT_REACHED: 'LOAD_ACTIVE_LIMIT_REACHED',

  // --- taklif ---
  OFFER_OWN_LOAD: 'OFFER_OWN_LOAD',
  OFFER_DUPLICATE: 'OFFER_DUPLICATE',
  OFFER_ALREADY_HANDLED: 'OFFER_ALREADY_HANDLED',
  OFFER_EXPIRED: 'OFFER_EXPIRED',
  OFFER_PRICE_REQUIRED: 'OFFER_PRICE_REQUIRED',
  OFFER_PRICE_OUT_OF_RANGE: 'OFFER_PRICE_OUT_OF_RANGE',

  // --- buyurtma ---
  ORDER_INVALID_TRANSITION: 'ORDER_INVALID_TRANSITION',
  ORDER_ACTOR_NOT_ALLOWED: 'ORDER_ACTOR_NOT_ALLOWED',
  ORDER_CONTACTS_ALREADY_VISIBLE: 'ORDER_CONTACTS_ALREADY_VISIBLE',

  // --- chat ---
  CHAT_CLOSED: 'CHAT_CLOSED',
  CHAT_MESSAGE_EMPTY: 'CHAT_MESSAGE_EMPTY',
  CHAT_ATTACHMENT_MISSING: 'CHAT_ATTACHMENT_MISSING',

  // --- kuzatuv ---
  TRACKING_NOT_ACTIVE: 'TRACKING_NOT_ACTIVE',

  // --- hamyon va toʻlov ---
  WALLET_ACCOUNT_NOT_FOUND: 'WALLET_ACCOUNT_NOT_FOUND',
  WALLET_INSUFFICIENT_FUNDS: 'WALLET_INSUFFICIENT_FUNDS',
  WALLET_LOCKED: 'WALLET_LOCKED',
  PAYMENT_NOT_FOUND: 'PAYMENT_NOT_FOUND',
  PAYMENT_ALREADY_PAID: 'PAYMENT_ALREADY_PAID',
  PAYMENT_AMOUNT_INVALID: 'PAYMENT_AMOUNT_INVALID',
  PAYMENT_PROVIDER_ERROR: 'PAYMENT_PROVIDER_ERROR',
  PAYOUT_TOO_SMALL: 'PAYOUT_TOO_SMALL',
  PAYOUT_ALREADY_PENDING: 'PAYOUT_ALREADY_PENDING',

  // --- reyting ---
  RATING_NOT_ALLOWED_YET: 'RATING_NOT_ALLOWED_YET',
  RATING_ALREADY_GIVEN: 'RATING_ALREADY_GIVEN',
  RATING_WINDOW_CLOSED: 'RATING_WINDOW_CLOSED',

  // --- fayl ---
  FILE_KEY_NOT_OWNED: 'FILE_KEY_NOT_OWNED',
  FILE_NOT_UPLOADED: 'FILE_NOT_UPLOADED',
  FILE_DELETE_FORBIDDEN: 'FILE_DELETE_FORBIDDEN',
} as const;

export type ErrorCodeValue = (typeof ErrorCode)[keyof typeof ErrorCode];
